# Site settings
title: Ryan Flynt and the Motel Ice Machine
email: ryaneflynt@gmail.com
description: Motel Ice Machine is an Americana band from Birmingham, Alabama blending honkytonk guitars and pedal steel with driving upright slap bass and blues harmonica.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://motelicemachine.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  motelicemachine


# Build settings
markdown: kramdown

# Outputting
permalink:     pretty

# collection settings
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
      categories: "news"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
